"""Print every prompt text the experiments use, verbatim from the code, as Markdown.

  python scripts/print_prompts.py > PROMPTS.md

Full prompts of example requests (system message with the tools, user message, outputs) are in
results/summary/agents_examples.md (choose-N teams) and results/summary/agents_bfcl_examples.md
(BFCL teams).
"""

import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from ptcdiag.data import agents, choose  # noqa: E402
from ptcdiag.data.paraprobe import WEATHER_FN  # noqa: E402
from ptcdiag.prompting import SYSTEM_TEMPLATE  # noqa: E402


def block(text):
    return ["```text", text.rstrip("\n"), "```", ""]


def main():
    out = ["# Prompt texts", "",
           "Generated by `scripts/print_prompts.py` from the constants in `ptcdiag/prompting.py`, "
           "`ptcdiag/data/choose.py` and `ptcdiag/data/agents.py`.", "",
           "## System message (every model, every condition)", "",
           "`{functions}` is the request's list of tool schemas as compact JSON. Models whose chat "
           "template has no system role get this text prepended to the first user message.", ""]
    out += block(SYSTEM_TEMPLATE.replace("{{", "{").replace("}}", "}"))
    out += ["## User message", "",
            "BFCL requests: the request text of BFCL v4 (`parallel`, `parallel_multiple`), unchanged.", "",
            "Choose-N requests (`data/choose.jsonl`, 105 requests, one tool):", "",
            "- list: `{context}Get the current weather in any {n} of these cities: {c1}, ..., {ck-1} and {ck}.` "
            "with n+3 listed cities",
            "- open: `{context}Get the current weather in {n} {phrase}.`", "",
            f"`{{n}}` is one of {', '.join(repr(w) for w in choose.WORDS.values())}; `{{context}}` one of "
            f"{', '.join(repr(c) for c in choose.CONTEXTS)}; `{{phrase}}` one of "
            f"{', '.join(repr(p) for p in choose.PHRASES)}.", "",
            "The choose-N tool:", ""]
    import json
    out += block(json.dumps(WEATHER_FN, ensure_ascii=False, indent=2))
    out += ["## Teams of agents: the note after the request", "",
            "Each agent's user message is the request text, a blank line, and one of these notes. "
            "`{i}` is the agent's number, `{n}` the team size, `{ordinal}` 'first' ... 'eighth', and "
            "`{calls}` either `none` or a JSON array of the calls made by the agents before it (an "
            "agent's raw output where it did not parse).", ""]
    for name, text in [("sim-anon (same time, anonymous)", agents.SIM_ANON),
                       ("sim-label (same time, numbered)", agents.SIM_LABEL),
                       ("sim-rule (same time, numbered, told the convention)", agents.SIM_RULE),
                       ("turn-anon (in turns, anonymous)", agents.TURN_ANON),
                       ("turn-label (in turns, numbered)", agents.TURN_LABEL)]:
        out += [f"### {name}", ""] + block(text)
    out += ["## Skeletons", "",
            "The dLLM writes its answer onto a canvas in which the skeleton fixes everything except the "
            "argument values (Section 3.1 of the paper); an AR model writes each value into the same "
            "skeleton until its closing token. A team agent gets the skeleton of its own call only; Dream "
            "agents decode it one token per step in confidence order, Qwen agents left to right. Examples of filled canvases, with the slots marked, are in "
            "`results/summary/closer.md`.", ""]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
